### ISSUE TITLE
Crash when calling FastPriorityQueue.kSmallest

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/jitdb#129]
This one was reported by @powersource

```
User comment: scrolling in our private chat

Stack trace from Node.js:
Invalid array length
RangeError: Invalid array length
    at FastPriorityQueue.OkkO4jAalwLOXHBTdh7R7K+1T2Qqc5+fwdcluN1YdKY=.FastPriorityQueue.kSmallest (/data/data/se.manyver/files/nodejs-project/index.js:38368:18)
    at getMessagesFromBitsetSlice (/data/data/se.manyver/files/nodejs-project/index.js:21008:23)
    at /data/data/se.manyver/files/nodejs-project/index.js:21036:9
    at /data/data/se.manyver/files/nodejs-project/index.js:20901:9
    at /data/data/se.manyver/files/nodejs-project/index.js:20850:11
    at /data/data/se.manyver/files/nodejs-project/index.js:20674:9
    at ensureIndexSync (/data/data/se.manyver/files/nodejs-project/index.js:20658:7)
    at filterIndex (/data/data/se.manyver/files/nodejs-project/index.js:20667:5)
    at getBitsetForOperation (/data/data/se.manyver/files/nodejs-project/index.js:20830:7)
    at /data/data/se.manyver/files/nodejs-project/index.js:20849:9
```

```
User comment: crash again

Stack trace from Node.js:
Invalid array length
RangeError: Invalid array length
    at FastPriorityQueue.OkkO4jAalwLOXHBTdh7R7K+1T2Qqc5+fwdcluN1YdKY=.FastPriorityQueue.kSmallest (/data/data/se.manyver/files/nodejs-project/index.js:38368:18)
    at getMessagesFromBitsetSlice (/data/data/se.manyver/files/nodejs-project/index.js:21008:23)
    at /data/data/se.manyver/files/nodejs-project/index.js:21036:9
    at /data/data/se.manyver/files/nodejs-project/index.js:20901:9
    at /data/data/se.manyver/files/nodejs-project/index.js:20850:11
    at /data/data/se.manyver/files/nodejs-project/index.js:20674:9
    at ensureIndexSync (/data/data/se.manyver/files/nodejs-project/index.js:20658:7)
    at filterIndex (/data/data/se.manyver/files/nodejs-project/index.js:20667:5)
    at getBitsetForOperation (/data/data/se.manyver/files/nodejs-project/index.js:20830:7)
    at /data/data/se.manyver/files/nodejs-project/index.js:20849:9
```

**Comment by staltz** [comment]
The line that says `Invalid array length` was this inside FastPriorityQueue:

```js
  var smallest = new Array(k)
```

So k is zero or negative. Or perhaps we shouldn't use Infinity here:

https://github.com/ssb-ngi-pointer/jitdb/blob/882253e9353f4ba7a354822220850a201ee79843/index.js#L1074

**Comment by arj03** [comment]
Right, this could happen if you do `paginate(-1)`. The infinity case actually means that you will get everything instead od 0 if you ask for `paginate(0)`. I feel like we should at least give some kind of error in that case with debug, and maybe return 0 results?
