### ISSUE TITLE
Crash: RangeError [ERR_OUT_OF_RANGE] with very large num

### ISSUE THREAD

**Issue by staltz** [ssb-ngi-pointer/jitdb#173]
For (not a lot) more details: https://gitlab.com/staltz/manyverse/-/issues/1487

```
The value of \\\"offset\\\" is out of range. It must be >= 0 and <= 65534. Received 75028
RangeError [ERR_OUT_OF_RANGE]: The value of \\\"offset\\\" is out of range. It must be >= 0 and <= 65534. Received 75028
    at boundsError (internal/buffer.js:81:9)
    at Buffer.readUInt16LE (internal/buffer.js:238:5)
    at Object.getDataNextOffset (/data/data/se.manyver/files/nodejs-project/index.js:50871:31)
    at Stream.RtIlCG2JhIOMRa4HMGBo5z/HYzUpKXF15L+qOV47dww=.Stream._handleBlock (/data/data/se.manyver/files/nodejs-project/index.js:31356:40)
    at Stream.RtIlCG2JhIOMRa4HMGBo5z/HYzUpKXF15L+qOV47dww=.Stream._resumeCallback (/data/data/se.manyver/files/nodejs-project/index.js:31427:24)
    at Request._callback (/data/data/se.manyver/files/nodejs-project/index.js:50830:9)
    at Request.Trwq+KqeWzxsbUet+Omb+wC9uH2QMBcZNBUiXOCqCv4=.Request.callback (/data/data/se.manyver/files/nodejs-project/index.js:33022:8)
    at onread (/data/data/se.manyver/files/nodejs-project/index.js:62999:31)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
```

**Comment by arj03** [comment]
This one is related to https://github.com/ssb-ngi-pointer/async-append-only-log/issues/11. I've taken a short look and will dedicate some time to try and get to the bottom of this issue.

**Comment by staltz** [comment]
Let's tentatively close this one and open another one if the issue resurfaces.
